### PR TITLE
Compass rose on map display

### PR DESCRIPTION
**Pull request by eugene-d**

### CODE REVIEW

**Comment by IanMayo** [comment]
@eugene-d - could you move the image down a few pixels, so that it doesn't cover the mission name?

compass

We don't need the leaflet compass plugin in the repo, do we?

**Comment by eugene-d** [comment]
@IanMayo Actually, yes, we can remove third party compass plugin and write simple own plugin. Also it should be possible to add the compass as we did mission name

**Comment by IanMayo** [comment]
Isn't the compass image a static image?  I was expecting that we'd just have the image, plus some CSS to put it onto the page.

**Comment by eugene-d** [comment]
@IanMayo you are right, it's static image

**Comment by IanMayo** [comment]
Cool, so is it possible for the PR to just contain the static image, plus the HTML/CSS modifications?

**Comment by eugene-d** [comment]
yes, I'll refactor this

**Comment by eugene-d** [comment]
@IanMayo check it, please

**Comment by IanMayo** [comment]
Great, thanks.

**Pull request merged**
