### PR TITLE
Detection path transparency

### PR DESCRIPTION
**Pull request by eugene-d**

### CODE REVIEW

**Comment by IanMayo** [comment]
There's quite a lot in this PR. I can see that the UI styling is just great.  

I'm interested in @alexnodejs opinions on the code implementation, particularly regarding JS patterns and/or possible performance improvement.

But, @alexnodejs  - I know this is a really complex part of Mustard.  I don't expect you gain a deep understanding of it (that would take weeks :-)  ). But, I would value a quick "look over".

thx.

**Comment by alexnodejs** [comment]
@IanMayo Already on it, I will provide some "imo" soon

**Comment by eugene-d** [comment]
@IanMayo @alexnodejs Guys, how it looks?

**Comment by alexnodejs** [comment]
@eugene-d looks good, as I understand @IanMayo will expand comments a bit as native english speaker :)

**Comment by IanMayo** [comment]
[comment tidied]

**Pull request merged**
